/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
  kotlin("jvm") version "1.3.50"
  id("com.github.johnrengelman.shadow") version "5.1.0"
  java
}

repositories {
  jcenter()
  maven {
    url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
  }
  maven {
    url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
  }
}

dependencies {
  implementation(kotlin("stdlib"))

  implementation("org.spigotmc:spigot-api:1.17-R0.1-SNAPSHOT")
  implementation("org.jetbrains.exposed:exposed:0.17.4")
  implementation("org.xerial:sqlite-jdbc:3.21.0.1")
  implementation("org.springframework.security:spring-security-core:5.2.0.RELEASE")
}

tasks.withType<KotlinCompile> {
  kotlinOptions.jvmTarget = "1.8"
}
